[package]
name = "vulkan_base"
version = "0.1.0"
authors = ["Lin Wang <wanglinseven@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.33.0"
winit = "0.25.0"
ash-window = "0.7"
cgmath = "0.18.0"

